### ISSUE TITLE
Termperature Conversion from C to F has error

### ISSUE THREAD

**Issue by KA1TW** [erainstruments/erasynth-micro-firmware#1]
The conversion from C to F temperature is not executing as intended.  F = C *(9/5) + 32 is the correct equation, but the compiled code is only adding 32.  

t *= (9 / 5);   // I think this is evaluating to "1" rather than 1.8
t += 32;

maybe try  t = t*1.8 + 32;   ... I'm an RF guy, not a programmer :)

**Comment by berjk** [comment]
Thank you for notice. Since we use metric system, were not aware of Fahrenheit was wrong. This was fixed at latest release: v1.0.7
